id: IF6216560
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:25:44.424181
last_modified: 2023-02-08 15:25:44.424295
source_metadata:
  title: Tathāgatagarbhasūtra
  language: zh
bases:
  F690:
    base_file: F690.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
